name: "Deploy CodigoFacilito"

on:
  push:
    branches: ["main"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    step:
      - uses: actions/checkout@v4
      - run: echo "Hacemos pull del codigo"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar version" 